gc:
  # remove all generations older than 7 days
  sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d
  # garbage collect all unused nix store entries
  sudo nix store gc --debug
update:
  nix flake update
commitlock:
  nix flake update --commit-lock-file
fmt:
  # format the nix files in this repo
  nix fmt